ycbv:
  - obj_000001
  - obj_000002
  - obj_000003
  - obj_000004
  - obj_000005
  - obj_000006
  - obj_000007
  - obj_000008
  - obj_000009
  - obj_000010
  - obj_000011
  - obj_000012
  - obj_000013
  - obj_000014
  - obj_000015
  - obj_000016
  - obj_000017
  - obj_000018
  - obj_000019
  - obj_000020
  - obj_000021

replicacad:
  - frl_apartment_basket
  - frl_apartment_beanbag
  - frl_apartment_bike_01
  - frl_apartment_bike_02
  - frl_apartment_bin_01
  - frl_apartment_bin_02
  - frl_apartment_bin_03
  - frl_apartment_book_01
  - frl_apartment_book_02
  - frl_apartment_book_03
  - frl_apartment_book_04
  - frl_apartment_book_05
  - frl_apartment_book_06
  - frl_apartment_bowl_01
  - frl_apartment_bowl_02
  - frl_apartment_bowl_03
  - frl_apartment_bowl_06
  - frl_apartment_bowl_07
  - frl_apartment_box
  - frl_apartment_cabinet
  - frl_apartment_camera_02
  - frl_apartment_chair_01
  - frl_apartment_chair_04
  - frl_apartment_chair_05
  - frl_apartment_choppingboard_02
  - frl_apartment_clock
  - frl_apartment_cloth_01
  - frl_apartment_cloth_02
  - frl_apartment_cloth_03
  - frl_apartment_cloth_04
  - frl_apartment_clothes_hanger_01
  - frl_apartment_clothes_hanger_02
  - frl_apartment_cup_01
  - frl_apartment_cup_02
  - frl_apartment_cup_03
  - frl_apartment_cup_05
  - frl_apartment_cushion_01
  - frl_apartment_cushion_03
  - frl_apartment_handbag
  - frl_apartment_indoor_plant_01
  - frl_apartment_indoor_plant_02
  - frl_apartment_kitchen_utensil_01
  - frl_apartment_kitchen_utensil_02
  - frl_apartment_kitchen_utensil_03
  - frl_apartment_kitchen_utensil_04
  - frl_apartment_kitchen_utensil_05
  - frl_apartment_kitchen_utensil_06
  - frl_apartment_kitchen_utensil_08
  - frl_apartment_kitchen_utensil_09
  - frl_apartment_knifeblock
  - frl_apartment_lamp_01
  - frl_apartment_lamp_02
  - frl_apartment_mat
  - frl_apartment_monitor
  - frl_apartment_monitor_stand
  - frl_apartment_pan_01
  - frl_apartment_picture_01
  - frl_apartment_picture_02
  - frl_apartment_picture_03
  - frl_apartment_picture_04
  - frl_apartment_plate_01
  - frl_apartment_plate_02
  - frl_apartment_rack_01
  - frl_apartment_refrigerator
  - frl_apartment_remote-control_01
  - frl_apartment_rug_01
  - frl_apartment_rug_02
  - frl_apartment_setupbox
  - frl_apartment_shoe_01
  - frl_apartment_shoe_02
  - frl_apartment_shoe_03
  - frl_apartment_shoe_04
  - frl_apartment_shoebox_01
  - frl_apartment_small_appliance_01
  - frl_apartment_small_appliance_02
  - frl_apartment_sofa
  - frl_apartment_sponge_dish
  - frl_apartment_stool_02
  - frl_apartment_table_01
  - frl_apartment_table_02
  - frl_apartment_table_03
  - frl_apartment_table_04
  - frl_apartment_towel
  - frl_apartment_tv_object
  - frl_apartment_tv_screen
  - frl_apartment_tvstand
  - frl_apartment_umbrella
  - frl_apartment_vase_01
  - frl_apartment_vase_02
  - frl_apartment_wall_cabinet_01
  - frl_apartment_wall_cabinet_02
  - frl_apartment_wall_cabinet_03
