spe3r:
  - acrimsat_final
  - apollo_soyuz_carbajal
  - aqua
  - aquarius_dep
  - aura_v002
  - bepi_mpo
  - bepi_mtm
  - calipso_v016_trip
  - cassini_66
  - chandra_v09
  - cheops
  - clementine_v01
  - cloudsat_v19
  - dawn_19
  - deep_space_1_11
  - double_star
  - giotto
  - grace_v011
  - hst
  - icesat_v015_uv_final
  - integral
  - jason-1_final
  - juice
  - juno
  - kepler_v009
  - lro_35
  - magellan_16
  - mars_global_surveyor
  - mars_odyssey
  - maven
  - messenger
  - mro_13
  - near_07
  - npp_16
  - ostm_jason-2
  - parkersolarprobe
  - philae
  - pioneer
  - planck
  - proba_2
  - proba_3_csc
  - proba_3_osc
  - quikscat_v006
  - rosetta
  - soho
  - solar_orbiter
  - sorce_vfinal
  - stardust_35
  - tdrs
  - terra_vfinal
  - tess
  - tgo_edm
  - themis
  - trmm_vfinal
  - venus_express
  - voyager_17
  - xmm_newton



















